=== ManuelsDAM/LND/LND/Alumnos/alumno.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="alumno">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="edad" type="xs:integer"/>
				<xs:element name="nota" type="xs:decimal" minOccurs="1" maxOccurs="10"/>
				<xs:element name="telefono" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ManuelsDAM/LND/LND/Alumnos/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumno xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/dam/Escritorio/LND/Alumnos/alumno.xsd">
    <nombre>Juan</nombre>
    <edad>25</edad>
    <nota>5</nota>
    <nota>6</nota>
    <nota>3.5</nota>
    <nota>7.8</nota>
    <telefono>603478625 </telefono>
    <telefono>603478626 </telefono>
</alumno>
